### PR TITLE
feat: config now includes settings

### PR DESCRIPTION
**Pull request by d2lam**
Now includes `settings`

Blocked by https://github.com/screwdriver-cd/data-schema/pull/107
Related to https://github.com/screwdriver-cd/screwdriver/issues/465

### CODE REVIEW

**Comment by minzcmu** [comment]
Can we have an example of addresses and statues in the test?

**Comment by d2lam** [comment]
@minz1027  It's not meant for email notification specifically. Just to test that it merges the settings in shared and job.

**Review by minzcmu — APPROVED** [review]
👍

**Review by tkyi — APPROVED** [review]
👍

**Pull request merged**
