### PR TITLE
feat: support overriding steps for templates

### PR DESCRIPTION
**Pull request by d2lam**
Allows override steps for templates

```
main:
   template: mytemplate@1
   steps: 
       - publish: echo not publishing
```

Translate into:
```
   steps:
       - test: echo test
       - publish: echo not publishing
```

Related: https://github.com/screwdriver-cd/screwdriver/issues/616

### CODE REVIEW

**Review by petey — APPROVED** [review]
`newJob` and `oldJob` are becoming somewhat confusing monikers for the inputs. The new/old variables make this additional snippet even more confusing without reading more context. We might want to refactor this in the future to something like `job` and `template` (or `jobTemplate`). Then you get something like `templateSteps` instead of `oldSteps` which makes a lot more sense with limited context.

**Comment by d2lam** [comment]
@petey I agree with you. It's pretty confusing. This function is used by merging `shared` as well, which is why I couldn't rename it to something like `templateJob` or `templateSteps`. If you have some suggestions for the names, I would be happy to incorporate it.

**Comment by tkyi** [comment]
`globalJobSettings` and `localJobSettings`? Or just `globalJob` and `localJob`? Arg idk.

**Review by minzcmu — APPROVED** [review]
👍 I think it's alright for now. Probably refactor the name later?

**Pull request merged**
